### PR TITLE
Add support for multiple portals of the same name

### PR DESCRIPTION
**Pull request by kainjow**
See #55

### CODE REVIEW

**Comment by jeremiahsmall** [comment]
I don't understand why you'd need this. Why would you have more than one portal of the same TO on the same layout? All portals referencing the same TO will contain the exact same data, and if you added more than one referencing the same TO, you'd have no way to differentiate them. This has nothing to do with SimpleFM. It's how the data is organized in the XML response.

**Comment by jeremiahsmall** [comment]
Assuming that there is a legitimate use case for this, the parser cannot simply be updated to support this, as that would be a serious backward compatibility break. If there is a legitimate use case, the change would need to be opt-in, so that it doesn't change the default result format.

**Comment by kainjow** [comment]
I am working with a database that I didn't write which has many portals for the same table. I suppose one could technically have multiple portals for the same table but have applied different formatting to entries, which could result in that data being overwritten with the layouts being merged.

It probably is a rare thing to do, and I just figured this would make the most sense, but I can understand it being a compatibility issue with the library. I can also just work with the library as it is, I'd rather not continue to use a forked version that may become outdated.

**Comment by jeremiahsmall** [comment]
You should consider making web-specific layouts instead of using existing ones. In fact, I consider it a best practice to create a web interface file with very optimized layouts. Remember that every portal will return all the data, and it will by definition be redundant for portals based on the same TO.

**Comment by jeremiahsmall** [comment]
If you decide to pursue this, please open a new PR that makes it an opt-in change.

**Comment by kainjow** [comment]
Great, thanks for the feedback.

**Pull request closed without merging**
